#!/usr/bin/env bash

. "$HOME"/share/wrtools-core/temp.bash 

temp_make_file stdout

test-run --stdout=/dev/null --stderr=/dev/null --exit-status=0 -- \
	xs-validate --catalog=test01-base-test/base-xsd/niem/xml-catalog.xml test01-base-test/iep-sample/Person.xml

cat << EOF > "$stdout"
$PWD/test01-base-test/iep-sample/Person.xml:3.58: error: cvc-elt.1.a: Cannot find the declaration of element 'nc:Person'.
EOF

test-run --stdout="$stdout" --stderr=/dev/null --exit-status=1 -- \
	xs-validate test01-base-test/iep-sample/Person.xml

test-run --stdout="$stdout" --stderr=/dev/null --exit-status=0 -- \
	xs-validate test01-base-test/iep-sample/Person-with-xsi-schemalocation.xml


